### PR TITLE
Added startup_script_s3_path and startup_script_s3_object_version arguments.

### PR DESCRIPTION
**Pull request by oddity-lapada**
* Added startup_script_s3_path and startup_script_s3_object_version arguments to the module to be able use these options from aws_mwaa_environment terraform resource.

### CODE REVIEW

**Review by dudymas — DISMISSED** [review]

**Comment by DustyShap** [comment]
@oddity-lapada any updates to these changes? Currently, not having the startup script is a blocker for us to deploy Airflow using the module.

**Comment by hans-d** [comment]
@oddity-lapada Hi, can you update the pr so that it passes the tests? otherwise, it is likely to be closed due to staleness.

**Pull request closed without merging**
